services:
  mysql:
    image: mysql:8.4
    container_name: pos-mysql
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - pos-mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pos-mysql-data: